### ISSUE TITLE
edit and delete buttons on project details page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#107]
On the project details page under the tab "Your Attestations the logged in user should have both the edit and delete attestation buttons.

![image](https://github.com/Giveth/DeVouch-FE/assets/67759413/cb1fd02c-9996-4852-84f9-9ffdadc59f31)

_Originally posted by @divine-comedian in https://github.com/Giveth/DeVouch-FE/issues/46#issuecomment-2154984882_

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf There is an issue with the UI not updating correctly after deleting or editing an attestation. Occasionally, when we fetch the attestations after 5 seconds, the updated data isn't included, causing the UI to remain unchanged. Updating the UI without a request is also challenging due to various edge cases like pagination, total counts, etc.

**Comment by divine-comedian** [comment]
first solution is wait 5 seconds then refetch data 
2nd option - update UI without fetching from the UI, just update what we have on the FE

1st one isn't working, waits 5 seconds, refetch the data and its not updated
2nd one is hard to apply, if we delete an attestation we have to care about pagination or edit attestation need to care about total counts or change attestation from vouch table to flag table

cherik - use useQuery hook? Do we run it every 5 seconds, because its not very optimized, refresh the data every 5 seconds, not a long term solution. We can utilize websocket feature of subsquid. If we are strict for it and get complaints from users we can go for it. 

showing loading message to a user or something, can take up to 10 seconds 

-----


let's increase refresh time to after 10 seconds and test if it works reliably.
