### ISSUE TITLE
checking for filtering options and reload when user clicks 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-FE#132]
when we are dealing with adding options to select a filter, we shouldn't reload the query when the user clicks on a filter box, we should only reload the projects with the selected filter queries when the user clicks away

submitted by @aminlatifi

**Comment by divine-comedian** [comment]
still need to do this one but low prio

**Comment by divine-comedian** [comment]
almost done, cherik is still checking an edge case, will leave a PR for it

**Comment by LatifatAbdullahi** [comment]
- when choosing filter options on project details page and project card user can select multiple options
- filtering is not applied until user is done selecting filtering options and clicks away to close filter menu
- filtering is applied correctly





@MohammadPCh 

It seems the current behaviour does not follow the AC, because  I can not select multiple options at once, I have to select an option, the filter is applied before I can select an extra option. Also based on the AC, the filter should be applied after Users have clicked away to close the filter modal.

Please kindly take a look.

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh 

**AC**

- When choosing filter options on project details page can select multiple options - **Pass**
- When choosing filter options on project card user can select multiple options - **Pass**
- Filtering is not applied until user is done selecting filtering options and clicks away to close filter menu - **Pass**
- Filtering is applied correctly - **Pass**
- Clear filter is applied correctly on  Project page - **Failed**
- Clear filter is applied correctly on  Project card - **Failed**

**Comment by MohammadPCh** [comment]
Thanks @LatifatAbdullahi 
could you please re-check it?
Thanks

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh @divine-comedian 

Thanks @MohammadPCh, the issues are now fixed

Test update - **Pass**

- When choosing filter options on project details page can select multiple options - Pass
- When choosing filter options on project card user can select multiple options - Pass
- Filtering is not applied until user is done selecting filtering options and clicks away to close filter menu - Pass
- Filtering is applied correctly - Pass
- Clear filter is applied correctly on Project page - **Pass**
- Clear filter is applied correctly on Project card - **Pass**
